<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        foreach ($this->checks() as [$table, $name, $expression]) {
            DB::statement("ALTER TABLE `{$table}` ADD CONSTRAINT `{$name}` CHECK ({$expression})");
        }
    }

    public function down(): void
    {
        foreach ($this->checks() as [$table, $name]) {
            DB::statement("ALTER TABLE `{$table}` DROP CHECK `{$name}`");
        }
    }

    /**
     * @return list<array{string, string, string}>
     */
    private function checks(): array
    {
        return [
            ['shop_addresses', 'ck_shop_addresses_cbccd3efcf', 'record_type IN (1, 2)'],
            ['shop_addresses', 'ck_shop_addresses_4a4d821ee4', 'position >= 0 AND JSON_TYPE(payload) = \'OBJECT\''],
            ['shop_addresses', 'ck_shop_addresses_4c7351308c', '(record_type = 1 AND shop_address_id IS NULL AND province_uuid IS NOT NULL AND municipality_uuid IS NOT NULL AND label IS NOT NULL AND CHAR_LENGTH(TRIM(label)) > 0) OR (record_type = 2 AND province_uuid IS NULL AND municipality_uuid IS NULL AND is_primary = FALSE)'],
            ['content_pages', 'ck_content_pages_d723ab0c74', 'page_kind IN (1, 2)'],
            ['content_pages', 'ck_content_pages_20f8a59249', '(page_kind = 1 AND product_id IS NULL AND type IS NOT NULL AND CHAR_LENGTH(TRIM(type)) > 0 AND canonical_url IS NULL) OR (page_kind = 2 AND product_id IS NOT NULL AND type IS NULL)'],
            ['media', 'ck_media_b762576c60', 'visibility IN (1, 2)'],
            ['media', 'ck_media_9039b28f88', 'position >= 0'],
            ['categories', 'ck_categories_cbccd3efcf', 'record_type IN (1, 2)'],
            ['categories', 'ck_categories_8ee34b862b', 'record_type <> 2 OR parent_id IS NULL'],
            ['products', 'ck_products_74be1e9e32', 'type IN (1, 2)'],
            ['products', 'ck_products_7fa97793e0', 'status IN (1, 2, 3)'],
            ['product_options', 'ck_product_options_cbccd3efcf', 'record_type IN (1, 2)'],
            ['product_options', 'ck_product_options_69bc03a819', 'display_type IS NULL OR display_type IN (1, 2, 3)'],
            ['product_options', 'ck_product_options_85d78dec00', 'CHAR_LENGTH(TRIM(name)) > 0'],
            ['product_options', 'ck_product_options_173662fe0f', '(record_type = 1 AND parent_id IS NULL AND identity_code IS NULL AND display_type IS NOT NULL AND display_type IN (1,2,3) AND color_hex IS NULL) OR (record_type = 2 AND parent_id IS NOT NULL AND identity_code IS NOT NULL AND CHAR_LENGTH(TRIM(identity_code)) > 0 AND display_type IS NULL)'],
            ['product_promotions', 'ck_product_promotions_a33b1bf065', 'discount_type IN (1, 2, 3)'],
            ['product_promotions', 'ck_product_promotions_01a1bbed62', 'minimum_quantity >= 1 AND value >= 0 AND (discount_type <> 1 OR value <= 100)'],
            ['product_reviews', 'ck_product_reviews_48b4e4fdb2', 'moderation_status IN (1, 2, 3, 4)'],
            ['product_reviews', 'ck_product_reviews_cb7681fbc4', 'note BETWEEN 1 AND 5'],
            ['visit_sessions', 'ck_visit_sessions_21a8950eba', 'device_type IS NULL OR device_type IN (1, 2, 3, 4)'],
            ['carts', 'ck_carts_24b1d83b73', 'status IN (1, 2, 3, 4)'],
            ['orders', 'ck_orders_c2a61bf48e', 'order_type IN (1, 2, 4)'],
            ['orders', 'ck_orders_c46158c9c6', 'channel IN (1, 2)'],
            ['orders', 'ck_orders_29eeb93249', 'commercial_status IN (1, 2, 5)'],
            ['orders', 'ck_orders_1a0a7f3619', '(confirmed_revision_id IS NULL AND validated_at IS NULL) OR (confirmed_revision_id IS NOT NULL AND validated_at IS NOT NULL)'],
            ['orders', 'ck_orders_0cbe16a436', 'commercial_status <> 2 OR (confirmed_revision_id IS NOT NULL AND validated_at IS NOT NULL)'],
            ['orders', 'ck_orders_836e3c99e9', '(order_type = 1 AND original_order_id IS NULL AND original_return_id IS NULL AND original_incident_id IS NULL AND original_incident_quantity IS NULL) OR (order_type = 2 AND original_order_id IS NOT NULL AND original_incident_id IS NOT NULL AND original_incident_quantity IS NOT NULL AND original_incident_quantity > 0) OR (order_type = 4 AND original_order_id IS NOT NULL AND original_return_id IS NOT NULL)'],
            ['orders', 'ck_orders_2a66eb60d4', '(original_incident_id IS NULL AND original_incident_quantity IS NULL) OR (original_incident_id IS NOT NULL AND original_incident_quantity IS NOT NULL AND original_incident_quantity > 0)'],
            ['order_revisions', 'ck_order_revisions_d4bb3f99ff', 'delivery_mode IN (1, 2)'],
            ['order_revisions', 'ck_order_revisions_e85e1d3359', 'shipping_charge_bearer IN (1, 2, 3)'],
            ['order_revisions', 'ck_order_revisions_150e82100d', 'revision_number > 0'],
            ['order_revisions', 'ck_order_revisions_a6e668f934', 'catalog_subtotal >= 0 AND applied_subtotal >= 0 AND customer_shipping_fee >= 0 AND shipping_discount >= 0 AND shipping_discount <= customer_shipping_fee AND merchant_shipping_amount >= 0 AND return_cost_recovery_amount >= 0 AND order_total >= 0 AND amount_to_collect = order_total AND order_total = applied_subtotal + customer_shipping_fee - shipping_discount + return_cost_recovery_amount'],
            ['order_revisions', 'ck_order_revisions_7cce9f903d', 'return_cost_recovery_amount = 0 OR (return_cost_recovery_reason IS NOT NULL AND CHAR_LENGTH(TRIM(return_cost_recovery_reason)) > 0)'],
            ['order_revisions', 'ck_order_revisions_04129ae066', '(delivery_mode = 1 AND pickup_point_uuid IS NULL AND pickup_point_snapshot IS NULL) OR (delivery_mode = 2 AND pickup_point_uuid IS NOT NULL AND pickup_point_snapshot IS NOT NULL)'],
            ['order_items', 'ck_order_items_d35bcee5a8', 'price_origin IN (1, 2, 3)'],
            ['order_items', 'ck_order_items_565fd683da', 'reservation_status IS NULL OR reservation_status IN (1, 2, 3)'],
            ['order_items', 'ck_order_items_121bbc4df0', 'quantity > 0 AND catalog_unit_price >= 0 AND applied_unit_price >= 0 AND unit_cost_snapshot >= 0 AND line_total = ROUND(quantity * applied_unit_price, 2)'],
            ['order_items', 'ck_order_items_038c49efa6', 'price_origin <> 3 OR (is_price_overridden = TRUE AND price_change_reason IS NOT NULL AND CHAR_LENGTH(TRIM(price_change_reason)) > 0 AND promotion_id IS NULL)'],
            ['order_items', 'ck_order_items_b1462d1a6c', '(reservation_status IS NULL AND reserved_at IS NULL AND reservation_released_at IS NULL AND reservation_created_at IS NULL AND reservation_updated_at IS NULL) OR (reservation_status IS NOT NULL AND reservation_status IN (1,2,3) AND reserved_at IS NOT NULL AND reservation_created_at IS NOT NULL AND reservation_updated_at IS NOT NULL AND ((reservation_status = 2 AND reservation_released_at IS NOT NULL) OR (reservation_status IN (1,3) AND reservation_released_at IS NULL)))'],
            ['order_history', 'ck_order_history_616f0b9b05', 'contact_outcome IS NULL OR contact_outcome IN (1, 2, 3, 4, 5)'],
            ['order_history', 'ck_order_history_087d067085', 'previous_status IS NULL OR previous_status IN (1, 2, 5)'],
            ['order_history', 'ck_order_history_e985cb7e6c', 'new_status IS NULL OR new_status IN (1, 2, 5)'],
            ['order_history', 'ck_order_history_762cba2a33', 'origin IN (1, 2, 3, 4)'],
            ['stock_movements', 'ck_stock_movements_45b46352b9', 'type IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)'],
            ['stock_movements', 'ck_stock_movements_c7ec7c1fde', 'variant_sequence > 0 AND physical_before >= 0 AND physical_after >= 0 AND reserved_before >= 0 AND reserved_after >= 0 AND quarantine_before >= 0 AND quarantine_after >= 0 AND reserved_after <= physical_after AND physical_after = physical_before + physical_delta AND reserved_after = reserved_before + reserved_delta AND quarantine_after = quarantine_before + quarantine_delta'],
            ['order_returns', 'ck_order_returns_fa22e728b3', 'reason IN (1, 2, 3, 4, 5, 6)'],
            ['order_returns', 'ck_order_returns_5648823bc2', 'status IN (1, 2, 3, 4, 5, 6)'],
            ['shipping_providers', 'ck_shipping_providers_b217f304d0', 'type IN (1, 2, 3)'],
            ['shipping_providers', 'ck_shipping_providers_b19c289e66', '(type = 1 AND carrier_account_id IS NOT NULL) OR (type IN (2,3) AND carrier_account_id IS NULL AND reference_configuration IS NULL)'],
            ['shipping_rates', 'ck_shipping_rates_43077a12e1', 'record_type IN (1, 2, 3)'],
            ['shipping_rates', 'ck_shipping_rates_7e434ba4b2', 'delivery_mode IS NULL OR delivery_mode IN (1, 2)'],
            ['shipping_rates', 'ck_shipping_rates_2ef5f84da4', 'service_type IS NULL OR service_type IN (1, 2)'],
            ['shipping_rates', 'ck_shipping_rates_6bf2cd7466', 'source IS NULL OR source IN (1, 2)'],
            ['shipping_rates', 'ck_shipping_rates_32e629f93a', 'amount >= 0'],
            ['shipping_rates', 'ck_shipping_rates_3a9ed07042', '(record_type = 1 AND province_uuid IS NOT NULL AND delivery_mode IS NOT NULL AND service_type IS NOT NULL AND service_type = 1 AND provider_id IS NULL AND carrier_account_id IS NULL AND created_by_id IS NULL AND source IS NULL AND retrieved_at IS NULL AND starts_at IS NULL AND ends_at IS NULL) OR (record_type = 2 AND provider_id IS NOT NULL AND province_uuid IS NOT NULL AND delivery_mode IS NOT NULL AND service_type IS NOT NULL AND source IS NOT NULL AND carrier_account_id IS NULL AND created_by_id IS NULL AND starts_at IS NULL AND ends_at IS NULL) OR (record_type = 3 AND carrier_account_id IS NOT NULL AND created_by_id IS NOT NULL AND source IS NOT NULL AND starts_at IS NOT NULL AND provider_id IS NULL AND province_uuid IS NULL AND municipality_uuid IS NULL AND delivery_mode IS NULL AND service_type IS NULL AND retrieved_at IS NULL AND deleted_at IS NULL)'],
            ['shipping_rates', 'ck_shipping_rates_cd8e300e14', 'ends_at IS NULL OR (starts_at IS NOT NULL AND ends_at > starts_at)'],
            ['free_shipping_rules', 'ck_free_shipping_rules_7e434ba4b2', 'delivery_mode IS NULL OR delivery_mode IN (1, 2)'],
            ['shipments', 'ck_shipments_d4bb3f99ff', 'delivery_mode IN (1, 2)'],
            ['shipments', 'ck_shipments_d79711973a', 'status IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)'],
            ['shipments', 'ck_shipments_f6025185b0', '(delivery_mode = 1 AND pickup_point_uuid IS NULL) OR (delivery_mode = 2 AND pickup_point_uuid IS NOT NULL)'],
            ['shipment_events', 'ck_shipment_events_66336a6c15', 'logistics_status IS NULL OR logistics_status IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)'],
            ['shipment_events', 'ck_shipment_events_fb5026231d', 'financial_status IS NULL OR financial_status IN (1, 2, 3, 4, 5, 6, 7)'],
            ['shipment_events', 'ck_shipment_events_2799f40951', 'source IN (1, 2, 3)'],
            ['carrier_operations', 'ck_carrier_operations_c35f401b6b', 'type IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)'],
            ['carrier_operations', 'ck_carrier_operations_e38744cd9b', 'status IN (1, 2, 3, 4, 5, 6, 7, 8)'],
            ['carrier_operations', 'ck_carrier_operations_8a9891f71d', 'attempts_count >= 0'],
            ['collections', 'ck_collections_f86ea7204d', 'declared_status IN (1, 2, 3, 4, 5, 6, 7)'],
            ['collections', 'ck_collections_4cd585b5b2', 'expected_amount >= 0 AND (declared_collected_amount IS NULL OR declared_collected_amount >= 0)'],
            ['remittance_statements', 'ck_remittance_statements_6d22a845c0', 'type IN (1, 2, 3, 4, 5)'],
            ['remittance_statements', 'ck_remittance_statements_5648823bc2', 'status IN (1, 2, 3, 4, 5, 6)'],
            ['remittance_statements', 'ck_remittance_statements_b6c681f7ca', 'expected_net_amount = gross_amount - fee_amount'],
            ['carrier_settlement_lines', 'ck_carrier_settlement_lines_20dcc1d4c8', 'record_type IN (1, 2, 3, 4)'],
            ['carrier_settlement_lines', 'ck_carrier_settlement_lines_5adf21351a', 'fee_payment_mode IS NULL OR fee_payment_mode IN (1, 2, 3, 4)'],
            ['carrier_settlement_lines', 'ck_carrier_settlement_lines_6587316d76', 'receivable_settlement_type IS NULL OR receivable_settlement_type IN (1, 2, 3, 4)'],
            ['carrier_settlement_lines', 'ck_carrier_settlement_lines_2cfb962f81', '(reversal_of_id IS NULL AND amount > 0) OR (reversal_of_id IS NOT NULL AND amount < 0)'],
            ['carrier_settlement_lines', 'ck_carrier_settlement_lines_7a4a411e63', 'carrier_fee_id IS NULL OR shipment_id IS NOT NULL'],
            ['carrier_settlement_lines', 'ck_carrier_settlement_lines_34d48037c9', '(record_type = 1 AND collection_id IS NOT NULL AND shipment_id IS NOT NULL AND remittance_statement_id IS NOT NULL AND carrier_fee_id IS NULL AND receivable_id IS NULL AND replacement_order_id IS NULL AND proof_media_id IS NULL AND fee_payment_mode IS NULL AND receivable_settlement_type IS NULL AND reason IS NULL AND external_reference IS NULL AND performed_at IS NULL) OR (record_type = 2 AND carrier_fee_id IS NOT NULL AND shipment_id IS NOT NULL AND remittance_statement_id IS NOT NULL AND fee_payment_mode IS NOT NULL AND fee_payment_mode IN (2,3) AND collection_id IS NULL AND receivable_id IS NULL AND replacement_order_id IS NULL AND proof_media_id IS NULL AND receivable_settlement_type IS NULL AND reason IS NULL AND external_reference IS NULL AND performed_at IS NULL) OR (record_type = 3 AND receivable_id IS NOT NULL AND receivable_settlement_type IS NOT NULL AND performed_at IS NOT NULL AND collection_id IS NULL AND replacement_order_id IS NULL AND fee_payment_mode IS NULL AND reason IS NULL) OR (record_type = 4 AND shipment_id IS NOT NULL AND remittance_statement_id IS NOT NULL AND reason IS NOT NULL AND external_reference IS NOT NULL AND collection_id IS NULL AND carrier_fee_id IS NULL AND receivable_id IS NULL AND fee_payment_mode IS NULL AND receivable_settlement_type IS NULL AND performed_at IS NULL)'],
            ['carrier_settlement_lines', 'ck_carrier_settlement_lines_8cede90479', 'record_type <> 3 OR ((carrier_fee_id IS NULL AND shipment_id IS NULL) OR (carrier_fee_id IS NOT NULL AND shipment_id IS NOT NULL))'],
            ['carrier_settlement_lines', 'ck_carrier_settlement_lines_044f31e656', 'record_type <> 3 OR receivable_settlement_type <> 1 OR (remittance_statement_id IS NOT NULL AND proof_media_id IS NOT NULL AND carrier_fee_id IS NULL)'],
            ['carrier_settlement_lines', 'ck_carrier_settlement_lines_6c0688ee99', 'record_type <> 3 OR receivable_settlement_type <> 2 OR carrier_fee_id IS NOT NULL'],
            ['carrier_settlement_lines', 'ck_carrier_settlement_lines_22092f3da9', 'record_type <> 3 OR receivable_settlement_type <> 3 OR remittance_statement_id IS NOT NULL'],
            ['expenses', 'ck_expenses_24b1d83b73', 'status IN (1, 2, 3, 4)'],
            ['expenses', 'ck_expenses_2cfb962f81', '(reversal_of_id IS NULL AND amount > 0) OR (reversal_of_id IS NOT NULL AND amount < 0)'],
            ['customer_adjustments', 'ck_customer_adjustments_b377d3055f', 'amount_kind IN (1, 2, 3)'],
            ['customer_adjustments', 'ck_customer_adjustments_b217f304d0', 'type IN (1, 2, 3)'],
            ['customer_adjustments', 'ck_customer_adjustments_757dbec8d7', 'status IN (1, 2, 3, 4, 5)'],
            ['customer_adjustments', 'ck_customer_adjustments_2cfb962f81', '(reversal_of_id IS NULL AND amount > 0) OR (reversal_of_id IS NOT NULL AND amount < 0)'],
            ['activity_log', 'ck_activity_log_762cba2a33', 'origin IN (1, 2, 3, 4)'],
            ['activity_log', 'ck_activity_log_6a73f15349', '(subject_type IS NULL AND subject_id IS NULL) OR (subject_type IS NOT NULL AND subject_id IS NOT NULL)'],
            ['activity_log', 'ck_activity_log_04eb33cd66', '(causer_type IS NULL AND causer_id IS NULL) OR (causer_type IS NOT NULL AND causer_id IS NOT NULL)'],
            ['activity_log', 'ck_activity_log_223500de31', 'log_name IS NULL OR log_name <> \'privacy\' OR performed_at IS NOT NULL'],
            ['carrier_fees', 'ck_carrier_fees_b2dfe7a5c9', 'fee_type IN (1, 2, 3, 4, 5, 6)'],
            ['carrier_fees', 'ck_carrier_fees_2933c18fd6', 'payer IN (1, 2, 3, 4)'],
            ['carrier_fees', 'ck_carrier_fees_cfe9b872b9', 'settlement_mode IN (1, 2, 3, 4)'],
            ['carrier_fees', 'ck_carrier_fees_757dbec8d7', 'status IN (1, 2, 3, 4, 5)'],
            ['carrier_fees', 'ck_carrier_fees_09636ef52f', '(reversal_of_id IS NULL AND (amount > 0 OR (fee_type = 2 AND amount = 0 AND rate_snapshot IS NOT NULL))) OR (reversal_of_id IS NOT NULL AND (amount < 0 OR (fee_type = 2 AND amount = 0 AND rate_snapshot IS NOT NULL)))'],
            ['carrier_fees', 'ck_carrier_fees_ef8e97d3fa', 'source_rate_id IS NULL OR carrier_account_id IS NOT NULL'],
            ['carrier_receivables', 'ck_carrier_receivables_757dbec8d7', 'status IN (1, 2, 3, 4, 5)'],
            ['carrier_receivables', 'ck_carrier_receivables_2d5d3fad6e', '(reversal_of_id IS NULL AND initial_amount > 0 AND remaining_amount >= 0 AND remaining_amount <= initial_amount) OR (reversal_of_id IS NOT NULL AND initial_amount < 0 AND remaining_amount = 0)'],
            ['invoices', 'ck_invoices_6ed49a29e3', 'document_type IN (1, 2)'],
            ['invoices', 'ck_invoices_24b1d83b73', 'status IN (1, 2, 3, 4)'],
            ['invoices', 'ck_invoices_204a0bea84', '(sequence_id IS NULL AND fiscal_year IS NULL AND sequence_number IS NULL AND number IS NULL) OR (sequence_id IS NOT NULL AND fiscal_year IS NOT NULL AND sequence_number IS NOT NULL AND number IS NOT NULL AND sequence_number > 0)'],
            ['invoices', 'ck_invoices_5730245384', 'status NOT IN (2,4) OR (sequence_id IS NOT NULL AND fiscal_year IS NOT NULL AND sequence_number IS NOT NULL AND number IS NOT NULL)'],
            ['invoices', 'ck_invoices_d8e5eabe59', 'status <> 2 OR (media_id IS NOT NULL AND issued_at IS NOT NULL)'],
            ['invoices', 'ck_invoices_fc86a60810', 'status <> 3 OR (cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL AND CHAR_LENGTH(TRIM(cancellation_reason)) > 0)'],
            ['invoices', 'ck_invoices_6a6e395233', '(document_type = 1 AND original_invoice_id IS NULL) OR (document_type = 2 AND original_invoice_id IS NOT NULL AND document_reason IS NOT NULL AND CHAR_LENGTH(TRIM(document_reason)) > 0)'],
            ['order_incidents', 'ck_order_incidents_5648823bc2', 'status IN (1, 2, 3, 4, 5, 6)'],
            ['order_incidents', 'ck_order_incidents_b4842e4640', 'affected_quantity > 0 AND eligible_product_amount >= 0 AND eligible_shipping_amount >= 0'],
            ['order_incident_details', 'ck_order_incident_details_48ce8520fc', 'type IN (1, 2, 3, 4, 5, 6)'],
            ['order_incident_details', 'ck_order_incident_details_c2363b9cc2', 'quantity > 0 AND CHAR_LENGTH(TRIM(reason)) > 0'],
            ['billing_rules', 'ck_billing_rules_cbccd3efcf', 'record_type IN (1, 2)'],
            ['billing_rules', 'ck_billing_rules_25f4ff1481', 'document_type IS NULL OR document_type IN (1, 2)'],
            ['billing_rules', 'ck_billing_rules_6dac4dd1df', 'policy_status IS NULL OR policy_status IN (1, 2, 3, 4)'],
            ['billing_rules', 'ck_billing_rules_5cb41c211e', '(record_type = 1 AND document_type IS NOT NULL AND fiscal_year IS NOT NULL AND shop_prefix IS NOT NULL AND next_number IS NOT NULL AND next_number > 0 AND code IS NULL AND version IS NULL AND trigger_event IS NULL AND numbering_scope IS NULL AND parameters IS NULL AND policy_status IS NULL AND return_resend_rule IS NULL AND validated_by_id IS NULL AND validated_at IS NULL AND validation_reference IS NULL AND effective_at IS NULL AND ends_at IS NULL) OR (record_type = 2 AND document_type IS NULL AND fiscal_year IS NULL AND shop_prefix IS NULL AND next_number IS NULL AND code IS NOT NULL AND version IS NOT NULL AND trigger_event IS NOT NULL AND numbering_scope IS NOT NULL AND parameters IS NOT NULL AND policy_status IS NOT NULL AND return_resend_rule IS NOT NULL AND version > 0 AND numbering_scope = \'shop\')'],
            ['billing_rules', 'ck_billing_rules_64506bf607', 'policy_status IS NULL OR policy_status NOT IN (2,3) OR (validated_by_id IS NOT NULL AND validated_at IS NOT NULL AND validation_reference IS NOT NULL AND seller_profile_version IS NOT NULL)'],
            ['billing_rules', 'ck_billing_rules_7b93dc0447', 'policy_status IS NULL OR policy_status <> 3 OR effective_at IS NOT NULL'],
            ['billing_rules', 'ck_billing_rules_4b77689abb', 'ends_at IS NULL OR (effective_at IS NOT NULL AND ends_at > effective_at)'],
            ['sales_terms_acceptances', 'ck_sales_terms_acceptances_e3e8885ec1', 'acceptance_mode IN (1, 2)'],
            ['billing_obligations', 'ck_billing_obligations_6ed49a29e3', 'document_type IN (1, 2)'],
            ['billing_obligations', 'ck_billing_obligations_757dbec8d7', 'status IN (1, 2, 3, 4, 5)'],
            ['billing_obligations', 'ck_billing_obligations_94d6fb8bde', 'attempts_count >= 0 AND (status <> 3 OR invoice_id IS NOT NULL)'],
            ['billing_obligations', 'ck_billing_obligations_ef15b128ff', '(document_type = 1 AND original_invoice_id IS NULL) OR (document_type = 2 AND original_invoice_id IS NOT NULL)'],
            ['commercial_corrections', 'ck_commercial_corrections_b9b48b20e3', 'correction_type IN (1, 2, 4, 5, 6, 7)'],
            ['commercial_corrections', 'ck_commercial_corrections_24b1d83b73', 'status IN (1, 2, 3, 4)'],
            ['commercial_corrections', 'ck_commercial_corrections_4c6b56fe7e', 'non_product_kind IN (1, 2, 3, 4)'],
            ['commercial_corrections', 'ck_commercial_corrections_3d42799dd0', '(non_product_kind = 1 AND non_product_revenue_delta = 0) OR (non_product_kind <> 1 AND non_product_revenue_delta <> 0)'],
            ['users', 'ck_users_24b1d83b73', 'status IN (1, 2, 3, 4)'],
            ['users', 'ck_users_d2898f856e', 'membership_status IN (1, 2, 3, 4)'],
            ['users', 'ck_users_1a606ba59a', 'membership_status <> 1 OR joined_at IS NOT NULL'],
            ['contact_verifications', 'ck_contact_verifications_40f36046fc', 'channel IN (1, 2, 3)'],
            ['contact_verifications', 'ck_contact_verifications_8a9891f71d', 'attempts_count >= 0'],
            ['carrier_remittance_batches', 'ck_carrier_remittance_batches_7fa97793e0', 'status IN (1, 2, 3)'],
            ['carrier_remittance_batches', 'ck_carrier_remittance_batches_c3e7002eaa', 'status <> 2 OR (verified_net_amount IS NOT NULL AND validated_by_id IS NOT NULL AND received_at IS NOT NULL AND proof_media_id IS NOT NULL)'],
            ['permissions', 'ck_permissions_6bec899416', 'guard_name = \'tenant\''],
            ['permissions', 'ck_permissions_83cb87a4fe', 'name NOT LIKE \'saas.%\''],
            ['roles', 'ck_roles_6bec899416', 'guard_name = \'tenant\''],
            ['roles', 'ck_roles_85d78dec00', 'CHAR_LENGTH(TRIM(name)) > 0'],
            ['role_has_permissions', 'ck_role_has_permissions_61a9c661de', 'duration_days BETWEEN 1 AND 9999'],
            ['model_has_roles', 'ck_model_has_roles_1698446bcf', 'model_type = \'shop_user\''],
            ['model_has_permissions', 'ck_model_has_permissions_1698446bcf', 'model_type = \'shop_user\''],
            ['model_has_permissions', 'ck_model_has_permissions_a55ae2c2be', 'expires_at > assigned_at AND expires_at <= DATE_ADD(assigned_at, INTERVAL 9999 DAY)'],
            ['shop', 'ck_shop_160ec0da2d', 'singleton = 1'],
            ['product_variants', 'ck_product_variants_ea4c5d3e8b', 'physical_stock >= 0 AND reserved_stock >= 0 AND quarantine_stock >= 0 AND reserved_stock <= physical_stock'],
            ['product_variants', 'ck_product_variants_707ee5a007', 'sale_price >= 0 AND unit_cost >= 0 AND low_stock_threshold >= 0 AND (previous_price IS NULL OR previous_price >= 0)'],
            ['navigation_events', 'ck_navigation_events_12ef73d372', 'sales_page_id IS NULL OR product_id IS NOT NULL'],
            ['cart_items', 'ck_cart_items_82113324c8', 'quantity > 0'],
            ['return_items', 'ck_return_items_b495b66fe2', 'expected_quantity > 0 AND received_quantity >= 0 AND restocked_quantity >= 0 AND lost_quantity >= 0 AND quarantined_quantity >= 0 AND documented_missing_quantity >= 0 AND received_quantity <= expected_quantity AND received_quantity = restocked_quantity + lost_quantity + quarantined_quantity AND received_quantity + documented_missing_quantity <= expected_quantity'],
            ['return_items', 'ck_return_items_0a93295568', 'documented_missing_quantity = 0 OR (discrepancy_reason IS NOT NULL AND CHAR_LENGTH(TRIM(discrepancy_reason)) > 0)'],
            ['carrier_operation_attempts', 'ck_carrier_operation_attempts_d7e85a4503', 'attempt_number > 0 AND duration_ms >= 0'],
            ['collection_entries', 'ck_collection_entries_2cfb962f81', '(reversal_of_id IS NULL AND amount > 0) OR (reversal_of_id IS NOT NULL AND amount < 0)'],
            ['commercial_correction_lines', 'ck_commercial_correction_lines_5deaab7edb', 'affected_quantity > 0 AND reference_sale_amount >= 0'],
        ];
    }
};
